
CREATE TABLE TEMPORAL (
	iso_code					            VARCHAR2(50),
	continent					            VARCHAR2(50),
    location_					            VARCHAR2(50),
    date_						            VARCHAR2(50),
    total_cases		                        VARCHAR2(50),
    new_cases	                            VARCHAR2(50),
    new_cases_smoothed	                    VARCHAR2(50),
    total_deaths	                        VARCHAR2(50),
    new_deaths	                            VARCHAR2(50),
    new_deaths_smoothed	                    VARCHAR2(50),
    total_cases_per_million	                VARCHAR2(50),
    new_cases_per_million	                VARCHAR2(50),
    new_cases_smoothed_per_million	        VARCHAR2(50),
    total_deaths_per_million	            VARCHAR2(50),
    new_deaths_per_million	                VARCHAR2(50),
    new_deaths_smoothed_per_million	        VARCHAR2(50),
    reproduction_rate	                    VARCHAR2(50),
    icu_patients	                        VARCHAR2(50),
    icu_patients_per_million	            VARCHAR2(50),
    hosp_patients	                        VARCHAR2(50),
    hosp_patients_per_million	            VARCHAR2(50),
    weekly_icu_admissions	                VARCHAR2(50),
    weekly_icu_admissions_per_million	    VARCHAR2(50),
    weekly_hosp_admissions	                VARCHAR2(50),
    weekly_hosp_admissions_per_million	    VARCHAR2(50),
    new_tests	                            VARCHAR2(50),
    total_tests	                            VARCHAR2(50),
    total_tests_per_thousand	            VARCHAR2(50),
    new_tests_per_thousand	                VARCHAR2(50),
    new_tests_smoothed	                    VARCHAR2(50),
    new_tests_smoothed_per_thousand	        VARCHAR2(50),
    positive_rate	                        VARCHAR2(50),
    tests_per_case	                        VARCHAR2(50),
    tests_units	                            VARCHAR2(50),
    total_vaccinations	                    VARCHAR2(50),
	people_vaccinated	                    VARCHAR2(50),
    people_fully_vaccinated	                VARCHAR2(50),
    total_boosters	                        VARCHAR2(50),
    new_vaccinations	                    VARCHAR2(50),
    new_vaccinations_smoothed	            VARCHAR2(50),
    total_vaccinations_per_hundred	        VARCHAR2(50),
    people_vaccinated_per_hundred	        VARCHAR2(50),
    people_fully_vaccinated_per_hundred	    VARCHAR2(50),
    total_boosters_per_hundred	            VARCHAR2(50),
    new_vaccinations_smoothed_per_million	VARCHAR2(50),
    stringency_index	                    VARCHAR2(50),
    population	                            VARCHAR2(50),
    population_density	                    VARCHAR2(50),
    median_age	                            VARCHAR2(50),
    aged_65_older	                        VARCHAR2(50),
    aged_70_older	                        VARCHAR2(50),
    gdp_per_capita	                        VARCHAR2(50),
    extreme_poverty	                        VARCHAR2(50),
    cardiovasc_death_rate	                VARCHAR2(50),
    diabetes_prevalence	                    VARCHAR2(50),
    female_smokers	                        VARCHAR2(50),
    male_smokers	                        VARCHAR2(50),
    handwashing_facilities	                VARCHAR2(50),
    hospital_beds_per_thousand	            VARCHAR2(50),
    life_expectancy	                        VARCHAR2(50),
    human_development_index	                VARCHAR2(50),    
    excess_mortality_cumulative_absolute    VARCHAR2(50),
    excess_mortality_cumulative             VARCHAR2(50),
    excess_mortality 	                    VARCHAR2(50),
    excess_mortality_cumulative_per_million VARCHAR2(50)    
);


CREATE TABLE CONTINENT (
    code INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(50)
);

CREATE TABLE COUNTRY (
    iso_code VARCHAR2(10) NOT NULL,
    location VARCHAR2(50),

    code_ INTEGER
);

CREATE TABLE CASE_REGISTER (
    id_ INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    date_ DATE NOT NULL,
    new_cases INTEGER,
    new_cases_smoothed DECIMAL(10,3),
    new_cases_per_million DECIMAL(10,3),
    new_cases_smoothed_per_million DECIMAL(10,3),
    total_cases INTEGER,
    total_cases_per_million DECIMAL(10,3),

    iso_code_ VARCHAR2(10)
);


CREATE TABLE DEATH_REGISTER (
    id_ INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    date_ DATE NOT NULL,
    new_deaths INTEGER,
    new_deaths_smoothed DECIMAL(10,3),
    new_deaths_per_million DECIMAL(10,3),
    new_deaths_smoothed_per_million DECIMAL(10,3),
    total_deaths INTEGER,
    total_deaths_per_million DECIMAL(10,3),

    iso_code_ VARCHAR2(10)
);

CREATE TABLE INTENSIVE_PATIENTS (
    id_ INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    date_ DATE NOT NULL,
    icu_patients INTEGER,
    icu_patients_per_million DECIMAL(10,3),
    weekly_icu_admissions DECIMAL(10,3),
    weekly_icu_admissions_per_million DECIMAL(10,3),

    iso_code_ VARCHAR2(10)
);

CREATE TABLE HOSPITALIZED (
    id_ INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    date_ DATE NOT NULL,
    hosp_patients INTEGER,
    hosp_patients_per_million DECIMAL(10,3),
    weekly_hosp_admissions DECIMAL(10,3),
    weekly_hosp_admissions_per_million DECIMAL(10,3),

    iso_code_ VARCHAR2(10)
);

CREATE TABLE TEST_UNIT (
    code INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(50)
);

CREATE TABLE TEST_REGISTER (
    id_ INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    date_ DATE NOT NULL,
    new_tests INTEGER,
    total_tests INTEGER,
    total_tests_per_thousand DECIMAL(10,3),
    new_tests_per_thousand DECIMAL(10,3),
    new_tests_smoothed INTEGER,
    new_tests_smoothed_per_thousand DECIMAL(10,3),
    tests_per_case DECIMAL(10,3),
    positive_rate DECIMAL(10,3),

    iso_code_ VARCHAR2(10),
    code_testUnit_ INTEGER
);

CREATE TABLE VACCINATION (
    id_ INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    date_ DATE NOT NULL,
    total_vaccinations INTEGER,
    people_vaccinated INTEGER,
    people_fully_vaccinated INTEGER,
    total_boosters INTEGER,
    new_vaccinations INTEGER,
    new_vaccinations_smoothed INTEGER,
    total_vaccinations_per_hundred DECIMAL(10,3),
    people_vaccinated_per_hundred DECIMAL(10,3),
    people_fully_vaccinated_per_hundred DECIMAL(10,3),
    total_boosters_per_hundred DECIMAL(10,3),
    new_vaccinations_smoothed_per_million INTEGER,

    iso_code_ VARCHAR2(10)
);

CREATE TABLE COUNTRY_DETAIL (
    id_ INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    date_ DATE NOT NULL,
    reproduction_rate DECIMAL(10,3),
    stringency_index DECIMAL(10,3),
    population INTEGER,
    population_density DECIMAL(10,3),
    median_age DECIMAL(10,3),
    aged_65_older DECIMAL(10,3),
    aged_70_older DECIMAL(10,3),
    gdp_per_capita DECIMAL(10,3),
    extreme_poverty DECIMAL(10,3),
    cardiovasc_death_rate DECIMAL(10,3),
    diabetes_prevalence DECIMAL(10,3),
    female_smokers DECIMAL(10,3),
    male_smokers DECIMAL(10,3),
    handwashing_facilities DECIMAL(10,3),
    hospital_beds_per_thousand DECIMAL(10,3),
    life_expectancy DECIMAL(10,3),
    human_development_index DECIMAL(10,3),
    excess_mortality_cumulative_absolute    DECIMAL(10,3),
    excess_mortality_cumulative             DECIMAL(10,3),
    excess_mortality 	                    DECIMAL(10,3),
    excess_mortality_cumulative_per_million DECIMAL(30,15),

    iso_code_ VARCHAR2(10)
);

/* ====================== CONSTRAINTS ====================== */
/* CONTINENT */
ALTER TABLE CONTINENT ADD CONSTRAINT pk_continent PRIMARY KEY(code);
/* COUNTRY */
ALTER TABLE COUNTRY ADD CONSTRAINT pk_country PRIMARY KEY(iso_code);
ALTER TABLE COUNTRY ADD CONSTRAINT fk_country_continent
    FOREIGN KEY(code_) REFERENCES CONTINENT(code);
/* CASE_REGISTER */
ALTER TABLE CASE_REGISTER ADD CONSTRAINT pk_caseRegister PRIMARY KEY(id_);
ALTER TABLE CASE_REGISTER ADD CONSTRAINT fk_caseRegister_country
    FOREIGN KEY(iso_code_) REFERENCES COUNTRY(iso_code); 
    
/* DEATH_REGISTER */
ALTER TABLE DEATH_REGISTER ADD CONSTRAINT pk_deathRegister PRIMARY KEY(id_);
ALTER TABLE DEATH_REGISTER ADD CONSTRAINT fk_deathRegister_country
    FOREIGN KEY(iso_code_) REFERENCES COUNTRY(iso_code);
/* INTENSIVE_PATIENTS */
ALTER TABLE INTENSIVE_PATIENTS ADD CONSTRAINT pk_intensivePatients PRIMARY KEY(id_);
ALTER TABLE INTENSIVE_PATIENTS ADD CONSTRAINT fk_intensivePatients_country
    FOREIGN KEY(iso_code_) REFERENCES COUNTRY(iso_code);
/* HOSPITALIZED */
ALTER TABLE HOSPITALIZED ADD CONSTRAINT pk_hospitalized PRIMARY KEY(id_);
ALTER TABLE HOSPITALIZED ADD CONSTRAINT fk_hospitalized_country
    FOREIGN KEY(iso_code_) REFERENCES COUNTRY(iso_code);
/* TEST_UNIT */
ALTER TABLE TEST_UNIT ADD CONSTRAINT pk_testUnit PRIMARY KEY(code);
/* TEST_REGISTER */
ALTER TABLE TEST_REGISTER ADD CONSTRAINT pk_testRegister PRIMARY KEY(id_);
ALTER TABLE TEST_REGISTER ADD CONSTRAINT fk_testRegister_country
    FOREIGN KEY(iso_code_) REFERENCES COUNTRY(iso_code);
ALTER TABLE TEST_REGISTER ADD CONSTRAINT fk_testRegister_testUnit
    FOREIGN KEY(code_testUnit_) REFERENCES TEST_UNIT(code);
/* VACCINATION */
ALTER TABLE VACCINATION ADD CONSTRAINT pk_vaccination PRIMARY KEY(id_);
ALTER TABLE VACCINATION ADD CONSTRAINT fk_vaccination_country
    FOREIGN KEY(iso_code_) REFERENCES COUNTRY(iso_code);
/* COUNTRY_DETAIL */
ALTER TABLE COUNTRY_DETAIL ADD CONSTRAINT pk_countryDetail PRIMARY KEY(id_);
ALTER TABLE COUNTRY_DETAIL ADD CONSTRAINT fk_countryDetail_country
    FOREIGN KEY(iso_code_) REFERENCES COUNTRY(iso_code);
    
/* DELETA TABLES */
DROP TABLE COUNTRY_DETAIL;
DROP TABLE VACCINATION;
DROP TABLE TEST_REGISTER;
DROP TABLE HOSPITALIZED;
DROP TABLE INTENSIVE_PATIENTS;
DROP TABLE DEATH_REGISTER;
DROP TABLE CASE_REGISTER;
DROP TABLE TEST_UNIT;
DROP TABLE COUNTRY;
DROP TABLE CONTINENT;
DROP TABLE TEMPORAL;

